###################################################################################
##    Open Source Social Network - AntzCode DevDocker Automated Installer        ##
##                                                                               ##
##    @package   AntzCode                                                        ##
##    @author    AntzCode Ltd                                                    ##
##    @copyright (C) AntzCode Ltd                                                ##
##    @license   GPLv3 https://raw.githubusercontent.com/AntzCode/               ##
##                         opensource-socialnetwork-devdocker/main/LICENSE       ##
##    @link      https://github.com/AntzCode/opensource-socialnetwork-devdocker  ##
##                                                                               ##
###################################################################################

version: "3.7"
services:
  app:
    image: antzcode/apache-php-ubuntu:apache2-php8.3-noble
    ports:
      - 80:80
    volumes:
      - ./config/sites-enabled:/etc/apache2/sites-enabled
      - ./config/php.ini:/etc/php/7.4/apache2/php.ini
      - ./config/envvars:/etc/apache2/envvars
      - ./logs:/var/www/logs
      - ./ossn_data:/var/www/ossn_data
      - ./www:/var/www/html
  db:
    image: antzcode/mariadb-ubuntu:mariadb10.6-focal
    env_file: 
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/files:/var/lib/mysql-files
